### ISSUE TITLE
Weekly Scrum - 01/04/2021

### ISSUE THREAD

**Issue by shoaibkhan17** [shoaibkhan17/MiniShopify#24]
What have I done this week?
- Update shop UI and some backend changes
- Delete shop UI and some backend changes
- Discard shop changes
- Update UML and removed the arrows
- Users can no longer add empty tags (bug fix)
- Add fonts to the website 
- Fetch the shop products (client-side logic)
- Render the products
- Routing to open a shop and its products
- Backend controller fixes of delete, add and update product

What will I do next week? 
- Improve the website flow
- Add proper routing to navigate between user shops and all shops
- User should be only able to edit his shops
- Fix up UI styling and bug issues
- Work on add items to the cart 

What is holding me back?
- Nothing

**Comment by abdillahinur** [comment]
What have I done this week?
- Added Search Shop Name Functionality to Front-End
- Added Search Shop by Tags Functionality to Front-End

What will I do next week?
- Add Filter Shops so User Shops would be listed once logging in is complete
- Cart Backend Functionality
- Fix Search Shops/Tags UI
- Update testing as per Milestone 2 feedback

What is holding me back?
- Nothing at the moment

**Comment by TamerIbrahim97** [comment]
What have I done this week?

- Added the Create Shop functionality to the backend

What will I do next week?
- Work on the frontend to finish the Create Shop functionality.
- Update testing
What is holding me back?
- Nothing

**Comment by meetdigrajkar** [comment]
What have I done this week?
- Add Shop (front-end form & back-end end points)
- Add Product (front-end form & back-end end points)
- Signed-in users can only edit their own shops
- Signed-in users can only edit their own products
- Update, delete and add product functionality (back-end)

What will I do next week?
- API tests for add, delete and update shop
- API tests for add, delete and update products
- Checking out products in cart (back-end: removing checked out products from Firestore DB)

What is holding me back?
- Little knowledge of react & redux but learning as we progress..

**Comment by kamaluddinshakiri** [comment]
What have I done this week?
- Added Cart Component, along with its price, quantity and total 
- Added Cart Summary, Card Item
- Added map of cart items 
- Added images

What will I do next week?
- work on the backend of the Card 
- Testing

What is holding me back?
Nothing
